FROM ubuntu:20.04

LABEL maintainer="ismail.demir@investmentdataservices.com"
LABEL version="1.0"
LABEL description="Image for rule-based solution."

# no prompt during installation:
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y software-properties-common python3 python3-pip wget gfortran libopenblas-dev liblapack-dev libpng-dev libfreetype-dev libfontconfig unzip cmake fonts-ubuntu

COPY rule_based_pipeline/pdftohtml_mod/xpdf-4.02_mod.zip /app/xpdf-4.02_mod/
COPY rule_based_pipeline/pdftohtml_mod/cmake-config.txt.patch /app/xpdf-4.02_mod/
RUN cd /app/xpdf-4.02_mod/ && unzip xpdf-4.02_mod.zip && patch -u cmake-config.txt -i cmake-config.txt.patch && cd .. && mkdir xpdf_build && cd xpdf_build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_DISABLE_FIND_PACKAGE_Qt4=1 -DCMAKE_DISABLE_FIND_PACKAGE_Qt5Widgets=1 ../xpdf-4.02_mod && make -j && make install

COPY requirements.txt /app/
COPY libpng12-0_1.2.54-1ubuntu1.1+1_ppa0_eoan_amd64.deb /app/
RUN dpkg -i /app/libpng12-0_1.2.54-1ubuntu1.1+1_ppa0_eoan_amd64.deb && pip3 install -r /app/requirements.txt

WORKDIR /app/

