FROM ubuntu:20.04

LABEL maintainer="ismail.demir@investmentdataservices.com"
LABEL version="1.0"
LABEL description="Image for rule-based solution."

# no prompt during installation:
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y software-properties-common python3 python3-pip wget gfortran libopenblas-dev liblapack-dev libpng-dev libfreetype-dev libfontconfig

COPY requirements.txt /app/
COPY libpng12-0_1.2.54-1ubuntu1.1+1_ppa0_eoan_amd64.deb /app/
RUN dpkg -i /app/libpng12-0_1.2.54-1ubuntu1.1+1_ppa0_eoan_amd64.deb && pip3 install -r /app/requirements.txt

COPY ./ /app/

RUN chgrp -R 0 /app/ && chmod g=u /app/
RUN chmod -R a+x /app

WORKDIR /app/

RUN mkdir -p /app/server_logs
RUN chmod -R 777 /app/server_logs

#USER 1234

CMD ./entry.sh
