version: '2'
services:
  rule_based_pipeline:
    image: rule_based_pipeline
    volumes:
      - ../../data:/app/data
      - ../../log:/app/server_logs
    ports:
      - 8000:8000
  # model_pipeline:
  #   image: model_pipeline
  #   volumes:
  #     - ../../data:/app/data
  #   ports:
  #     - 6000:6000
  # esg_data_pipeline:
  #   image: esg_data_pipeline
  #   volumes:
  #     - ../../data:/app/data
  #   ports:
  #     - 4000:4000
  be:
    build:
      context: ./
      dockerfile: dockerfile_dev
    command: sanic de.app --dev --host=0.0.0.0 --port=1300
    environment:
      - FILE_PATH=/data
      - RBP_URL=host.docker.internal:8000
    volumes:
      - ./src:/de
      - ../../data:/data
    ports:
      - 18000:1300
    depends_on:
      - rule_based_pipeline
